### ISSUE TITLE
Sensible Default impls

### ISSUE THREAD

**Issue by srijs** [jimmycuadra/retry#10]
Would it be possible to provide sensible default impls of retry strategies (for instance a default base on exponential), or are we of the opinion that each use-case will require different setting, and therefore default impls wouldn't be a good idea?

**Comment by jimmycuadra** [comment]
It'd be hard to generalize without knowing use cases. A default for a type that has a an obvious "zero" value makes sense, but for these delays, a zero value specifically _doesn't_ make sense. I think it's better to be explicit.
