### ISSUE TITLE
Configurable multiplication factor in `retry::delay::Exponential`

### ISSUE THREAD

**Issue by SimonSapin** [jimmycuadra/retry#23]
Based on reading the current code:

https://github.com/jimmycuadra/retry/blob/ab48d2b467b04300414bf8cb0063ac074df43632/src/delay.rs#L20-L44

It looks like if I want the first delay to be one second (1_000 ms) then the second one will be 16 minutes (1_000_000 ms), the third one 11 days (1_000_000_000 ms), etc. It is exponential so it fits the doc-comment’s description, but it grows way too quickly to be useful.

Doubling at every step (1s, 2s, 4s, 8s, …) would seem more reasonable, but perhaps different use cases call for different factors. Perhaps this struct could gain a constructor with `first_in_millis: u64, factor: f64` parameters?

**Comment by jimmycuadra** [comment]
Good idea! Happy to take a PR for this if you wanna add it.
