### ISSUE TITLE
Improve the bus factor?

### ISSUE THREAD

**Issue by rbtcollins** [jimmycuadra/retry#39]
@jimmycuadra you say in https://github.com/jimmycuadra/retry/pull/31#issuecomment-787041706 that you don't do much free software nowadays.

Would you like to give maintainer access to this crate (on crates.io) and the repository here to someone / some people? Its a dependency for rustup, and seems like the maintenance is fairly low - we haven't had to touch it for some time, though we we also affected by #35.

**Comment by jimmycuadra** [comment]
Yes, this is a very good idea. Sam Rijs also has access but I'm not sure how active/available they are. I've added you as a collaborator on the repository as well as an owner of the project on crates.io. You're welcome to make any decisions on the project that are useful for rustup—I don't want my inactivity to block or harm rustup (or really any other project) in any way.

**Comment by rbtcollins** [comment]
Thank you!I've accepted the invite.
