### ISSUE TITLE
Fold `NoDelay` into `Fixed`?

### ISSUE THREAD

**Issue by srijs** [jimmycuadra/retry#9]
As things stand, `NoDelay` is really just a special case of `Fixed`. Should it continue to be a separate struct, or should we consider making it another constructor on `Fixed` (or maybe provide a default implementation for `Fixed` with that behaviour, similar to the `Duration` default impl)?

**Comment by jimmycuadra** [comment]
I think the key consideration here is what approach makes for a more intuitive API for users. The user doesn't particularly care how these delay structs are implemented, but it's valuable to them to be able to easily see a no-op delay by an obvious name as one of the structs in the module. While it would be functionally equivalent to use `Fixed::from_millis(0)`, that is less obvious and requires reading the documentation for `Fixed`.
